spring.application.name=CAServer
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/ca_db?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_APP_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:123456}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

# Forwarded headers from the API gateway (nginx)
server.forward-headers-strategy=native

# CA keystore
ca.keystore.dir=certs/ca
ca.keystore.filename=root-ca.p12
ca.keystore.password=${CA_KEYSTORE_PASSWORD:12345678}


ca.keystore.path=classpath:certs/ca/root-ca.p12
ca.key.alias=ca-key
ca.key.password=${CA_KEY_PASSWORD:12345678}